# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.3.1
_src_path: https://github.com/jupyterlab/extension-template
author_email: segurvich@ucsd.edu
author_name: Sergey Gurvich
data_format: string
file_extension: ''
has_binder: true
has_settings: false
kind: frontend
labextension_name: jupyterlab_apod
mimetype: ''
mimetype_name: ''
project_short_description: Show a random NASA Astronomy Picture of the Day in a JupyterLab
    panel
python_name: jupyterlab_apod
repository: https://github.com/sergeygurvich/jl-ext-test
test: true
viewer_name: ''

